description: "This page was created in order for me to understand how Jekyll and Github pages intertwine and work."
email: "lawrencetlee@g.ucla.edu"
twitter: "https://twitter.com/thecarpentries"

team_members:
  -
    name: "Tom Cat"
    role: "project lead"
    start_date: "2020-10-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
  -
    name: "Alice Dauncey"
    role: "developer"
    start_date: "2020-09-15"
collections:
  blogposts:
    output: true