name: Request User on Pull Request
on:
  pull_request:
    types:
      - opened

jobs:
  request_user:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Request User
        run: |
          npm install @octokit/rest
          node -e '
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const owner = process.env.GITHUB_REPOSITORY_OWNER;
            const repo = process.env.GITHUB_REPOSITORY;
            const pullRequestNumber = process.env.GITHUB_EVENT_PULL_REQUEST_NUMBER;
            const requestedUser = "lawtlee";

            octokit.issues.addAssignees({
              owner: owner,
              repo: repo,
              issue_number: pullRequestNumber,
              assignees: [requestedUser]
            })
            .then(() => {
              console.log(`User ${requestedUser} requested for pull request #${pullRequestNumber}`);
            })
            .catch((error) => {
              console.error(error);
              process.exit(1);
            });
          '