name: Request User on Pull Request
on:
  pull_request:
    types:
      - closed

jobs:
  email_patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Create Patch
        run: |
          git format-patch main -1 HEAD
      
      - name: Set up Git
        run: |
          git config user.name lawtlee
          git config user.email lawsac2947@gmail.com
      
      - name: Install send-email
        run: |
          sudo apt-get update
          sudo apt-get install -y git-email

      - name: Send Email
        run: |
          patch=$(ls | grep *.patch)
          git send-email --to=lawsac2947@gmail.com $(patch)

      - name: Delete Patch
        run: |
          rm $(ls | grep *.patch)
